# Generated by Django 4.2.6 on 2023-10-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_photo_user_alter_photo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='logo',
            field=models.FileField(blank=True, default='logos/album.jpeg', null=True, upload_to='logo'),
        ),
    ]
