# Generated by Django 4.2.6 on 2023-10-11 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_album_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumdetail',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(upload_to='photos', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Désignation'),
        ),
    ]
