# Generated by Django 4.2.6 on 2023-10-11 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_albumdetail_photo_alter_photo_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumdetail',
            name='photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.photo'),
            preserve_default=False,
        ),
    ]
